theme: minima
author: Muhammad Murtaza Tantry
exclude: ["README.md"]
skin: dark
github_username: murtazatantray
linkedin_username: muhammad-murtaza-tantry-21a1062b8
google_site_verification: OKRa9PKcvmG05oeRRX6unq9OVD1nGw7BRA34sFvnL48
